//
// RegisterPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RegisterPayload: Codable {

    public enum Role: String, Codable, CaseIterable {
        case helper = "helper"
        case seeker = "seeker"
        case _none = "none"
    }
    public var email: String
    public var firstName: String
    public var lastName: String
    public var role: Role? = ._none
    public var password: String

    public init(email: String, firstName: String, lastName: String, role: Role?, password: String) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.role = role
        self.password = password
    }

}
