# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'nexd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nexd
  pod 'Cleanse'
  pod 'NexdClient', :path => 'lib/openapi'
  pod 'R.swift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'SwiftLint'
  pod 'Validator'
  pod 'XCGLogger'

  target 'nexdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
