//
// ArticlesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RxSwift



open class ArticlesAPI {
    /**
     List articles
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<[Article]>
     */
    open class func articlesControllerFindAll(apiResponseQueue: DispatchQueue = NexdClientAPI.apiResponseQueue) -> Observable<[Article]> {
        return Observable.create { observer -> Disposable in
            articlesControllerFindAllWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    observer.onNext(response.body!)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     List articles
     - GET /articles
     - returns: RequestBuilder<[Article]> 
     */
    open class func articlesControllerFindAllWithRequestBuilder() -> RequestBuilder<[Article]> {
        let path = "/articles"
        let URLString = NexdClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Article]>.Type = NexdClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Create an article
     
     - parameter xAdminSecret: (header) Secret to access the admin functions. 
     - parameter createArticleDto: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<Article>
     */
    open class func articlesControllerInsertOne(xAdminSecret: String, createArticleDto: CreateArticleDto, apiResponseQueue: DispatchQueue = NexdClientAPI.apiResponseQueue) -> Observable<Article> {
        return Observable.create { observer -> Disposable in
            articlesControllerInsertOneWithRequestBuilder(xAdminSecret: xAdminSecret, createArticleDto: createArticleDto).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    observer.onNext(response.body!)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     Create an article
     - POST /articles
     - parameter xAdminSecret: (header) Secret to access the admin functions. 
     - parameter createArticleDto: (body)  
     - returns: RequestBuilder<Article> 
     */
    open class func articlesControllerInsertOneWithRequestBuilder(xAdminSecret: String, createArticleDto: CreateArticleDto) -> RequestBuilder<Article> {
        let path = "/articles"
        let URLString = NexdClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createArticleDto)

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-admin-secret": xAdminSecret.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Article>.Type = NexdClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

}
