//
// RegisterPayload.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegisterPayload: Codable {

    public var email: String
    public var firstName: String
    public var lastName: String
    public var password: String

    public init(email: String, firstName: String, lastName: String, password: String) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.password = password
    }


}

