//
// Article.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Article: Codable { 


    /** Auto-incremented id of an article. */
    public var id: Int
    /** Name of the article, should also contain the unit. */
    public var name: String

    public init(id: Int, name: String) {
        self.id = id
        self.name = name
    }

}
