//
// AvailableLanguages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum AvailableLanguages: String, Codable, CaseIterable {
    case de = "de"
    case en = "en"
}
