//
// AvailableLanguages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum AvailableLanguages: String, Codable, CaseIterable {
    case deDe = "de-DE"
    case enUs = "en-US"
}
