//
// BackendErrorEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BackendErrorEntry: Codable { 


    public enum ErrorCode: String, Codable, CaseIterable {
        case validationEmailInvalid = "VALIDATION_EMAIL_INVALID"
        case validationPhonenumberInvalid = "VALIDATION_PHONENUMBER_INVALID"
        case validationPasswordTooShort = "VALIDATION_PASSWORD_TOO_SHORT"
        case usersUserExists = "USERS_USER_EXISTS"
        case usersUserNotFound = "USERS_USER_NOT_FOUND"
    }
    /** Specific error code from enum */
    public var errorCode: ErrorCode
    public var errorDescription: String

    public init(errorCode: ErrorCode, errorDescription: String) {
        self.errorCode = errorCode
        self.errorDescription = errorDescription
    }

}
