//
// CallQueryDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CallQueryDto: Codable { 


    public var amount: Int?
    public var zip: Int?
    public var country: String?
    public var city: String?
    public var converted: Bool?

    public init(amount: Int?, zip: Int?, country: String?, city: String?, converted: Bool?) {
        self.amount = amount
        self.zip = zip
        self.country = country
        self.city = city
        self.converted = converted
    }

}
