//
// Call.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Call: Codable { 


    public var convertedHelpRequestId: Int64?
    public var sid: String
    public var createdAt: Date
    public var updatedAt: Date
    public var recordingUrl: String?
    public var phoneNumber: String?
    public var country: String?
    public var zip: String?
    public var city: String?
    public var converterId: String?
    public var converter: User?

    public init(convertedHelpRequestId: Int64?, sid: String, createdAt: Date, updatedAt: Date, recordingUrl: String?, phoneNumber: String?, country: String?, zip: String?, city: String?, converterId: String?, converter: User?) {
        self.convertedHelpRequestId = convertedHelpRequestId
        self.sid = sid
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.recordingUrl = recordingUrl
        self.phoneNumber = phoneNumber
        self.country = country
        self.zip = zip
        self.city = city
        self.converterId = converterId
        self.converter = converter
    }

}
