//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Category: Codable { 


    /** Auto-incremented ID of an category. */
    public var id: Int64
    /** Category name */
    public var name: String
    public var language: AvailableLanguages
    public var articles: [Article]?

    public init(id: Int64, name: String, language: AvailableLanguages, articles: [Article]?) {
        self.id = id
        self.name = name
        self.language = language
        self.articles = articles
    }

}
