//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Category: Codable { 


    public enum Language: String, Codable, CaseIterable {
        case deDe = "de-DE"
        case enUs = "en-US"
    }
    /** Auto-incremented ID of an category. */
    public var id: Int64
    /** Category name */
    public var name: String
    /** Language key of this category */
    public var language: Language
    public var articles: [Article]?

    public init(id: Int64, name: String, language: Language, articles: [Article]?) {
        self.id = id
        self.name = name
        self.language = language
        self.articles = articles
    }

}
