//
// ConvertedHelpRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ConvertedHelpRequestDto: Codable { 


    public var helpRequestId: Int

    public init(helpRequestId: Int) {
        self.helpRequestId = helpRequestId
    }

}
