//
// CreateArticleDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateArticleDto: Codable { 


    /** Name of the article, should also contain the unit. */
    public var name: String

    public init(name: String) {
        self.name = name
    }

}
