//
// CreateRequestArticleDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateRequestArticleDto: Codable {

    /** Article ID received from the article list */
    public var articleId: Int
    /** Number of items */
    public var articleCount: Int

    public init(articleId: Int, articleCount: Int) {
        self.articleId = articleId
        self.articleCount = articleCount
    }

}
