//
// CreateArticleDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateArticleDto: Codable { 


    /** Name of the article. If the name already exists, no new article will be added. */
    public var name: String
    public var language: AvailableLanguages

    public init(name: String, language: AvailableLanguages) {
        self.name = name
        self.language = language
    }

}
