//
// CreateArticleDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateArticleDto: Codable { 


    public enum Language: String, Codable, CaseIterable {
        case de = "de"
        case en = "en"
    }
    /** Name of the article. If the name already exists, no new article will be added. */
    public var name: String
    /** Language of the article, e.g. the user */
    public var language: Language

    public init(name: String, language: Language) {
        self.name = name
        self.language = language
    }

}
