//
// EmailPasswordResetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EmailPasswordResetDto: Codable { 


    public var email: String
    public var passwordResetToken: String
    public var password: String

    public init(email: String, passwordResetToken: String, password: String) {
        self.email = email
        self.passwordResetToken = passwordResetToken
        self.password = password
    }

}
