//
// HelpListCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HelpListCreateDto: Codable { 


    public enum Status: String, Codable, CaseIterable {
        case active = "active"
        case canceled = "canceled"
        case completed = "completed"
    }
    /** List of help request IDs */
    public var helpRequestsIds: [Int64]?
    public var status: Status? = .active

    public init(helpRequestsIds: [Int64]?, status: Status?) {
        self.helpRequestsIds = helpRequestsIds
        self.status = status
    }

}
