//
// HelpRequestCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HelpRequestCreateDto: Codable { 


    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case ongoing = "ongoing"
        case completed = "completed"
        case deactivated = "deactivated"
    }
    public var street: String?
    public var number: String?
    public var zipCode: String?
    public var city: String?
    public var articles: [CreateHelpRequestArticleDto]?
    public var status: Status? = .pending
    public var additionalRequest: String?
    public var deliveryComment: String?
    public var phoneNumber: String?

    public init(street: String?, number: String?, zipCode: String?, city: String?, articles: [CreateHelpRequestArticleDto]?, status: Status?, additionalRequest: String?, deliveryComment: String?, phoneNumber: String?) {
        self.street = street
        self.number = number
        self.zipCode = zipCode
        self.city = city
        self.articles = articles
        self.status = status
        self.additionalRequest = additionalRequest
        self.deliveryComment = deliveryComment
        self.phoneNumber = phoneNumber
    }

}
