//
// HelpRequestStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum HelpRequestStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case ongoing = "ongoing"
    case completed = "completed"
    case deactivated = "deactivated"
}
