//
// HelpRequestArticle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HelpRequestArticle: Codable { 


    public var articleId: Int64?
    public var articleCount: Int64?
    public var id: Int64?
    public var article: Article?
    public var articleDone: Bool?
    public var helpRequest: HelpRequest?

    public init(articleId: Int64?, articleCount: Int64?, id: Int64?, article: Article?, articleDone: Bool?, helpRequest: HelpRequest?) {
        self.articleId = articleId
        self.articleCount = articleCount
        self.id = id
        self.article = article
        self.articleDone = articleDone
        self.helpRequest = helpRequest
    }

}
