//
// HelpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HelpRequest: Codable { 


    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case ongoing = "ongoing"
        case completed = "completed"
        case deactivated = "deactivated"
    }
    public var street: String?
    public var number: String?
    public var zipCode: String?
    public var city: String?
    public var id: Int?
    public var createdAt: Date?
    public var priority: String?
    public var additionalRequest: String?
    public var deliveryComment: String?
    public var phoneNumber: String?
    public var status: Status?
    public var articles: [HelpRequestArticle]?
    public var requesterId: String?
    public var requester: User?
    public var helpListId: Int?
    public var helpList: HelpList?

    public init(street: String?, number: String?, zipCode: String?, city: String?, id: Int?, createdAt: Date?, priority: String?, additionalRequest: String?, deliveryComment: String?, phoneNumber: String?, status: Status?, articles: [HelpRequestArticle]?, requesterId: String?, requester: User?, helpListId: Int?, helpList: HelpList?) {
        self.street = street
        self.number = number
        self.zipCode = zipCode
        self.city = city
        self.id = id
        self.createdAt = createdAt
        self.priority = priority
        self.additionalRequest = additionalRequest
        self.deliveryComment = deliveryComment
        self.phoneNumber = phoneNumber
        self.status = status
        self.articles = articles
        self.requesterId = requesterId
        self.requester = requester
        self.helpListId = helpListId
        self.helpList = helpList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case street
        case number
        case zipCode
        case city
        case id
        case createdAt = "created_at"
        case priority
        case additionalRequest
        case deliveryComment
        case phoneNumber
        case status
        case articles
        case requesterId
        case requester
        case helpListId
        case helpList
    }

}
