//
// HttpBadRequestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HttpBadRequestResponse: Codable { 


    public var statusCode: Int64
    public var error: String
    public var message: [String]

    public init(statusCode: Int64, error: String, message: [String]) {
        self.statusCode = statusCode
        self.error = error
        self.message = message
    }

}
