//
// HttpConflictResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HttpConflictResponse: Codable { 


    public enum ErrorCode: String, Codable, CaseIterable {
        case usersUserExists = "USERS_USER_EXISTS"
    }
    public var statusCode: Int64
    /** Specific error code from enum */
    public var errorCode: ErrorCode
    public var errorDescription: String

    public init(statusCode: Int64, errorCode: ErrorCode, errorDescription: String) {
        self.statusCode = statusCode
        self.errorCode = errorCode
        self.errorDescription = errorDescription
    }

}
