//
// LoginDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LoginDto: Codable { 


    public var email: String
    public var password: String

    public init(email: String, password: String) {
        self.email = email
        self.password = password
    }

}
