//
// PhoneNumberDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PhoneNumberDto: Codable { 


    public var language: String
    public var country: String
    public var comment: String
    /** Valid phonenumber for libphonenumber */
    public var number: String

    public init(language: String, country: String, comment: String, number: String) {
        self.language = language
        self.country = country
        self.comment = comment
        self.number = number
    }

}
