//
// RegisterDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RegisterDto: Codable { 


    public var email: String
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String?
    public var password: String

    public init(email: String, firstName: String?, lastName: String?, phoneNumber: String?, password: String) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
        self.password = password
    }

}
