//
// RequestEntity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RequestEntity: Codable {

    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case ongoing = "ongoing"
        case completed = "completed"
    }
    public var street: String?
    public var number: String?
    public var zipCode: String?
    public var city: String?
    public var id: Int
    public var createdAt: Date
    public var requesterId: Int
    public var priority: String
    public var additionalRequest: String
    public var deliveryComment: String
    public var phoneNumber: String
    public var status: Status = .pending
    public var articles: [RequestArticle]
    public var requester: User?

    public init(street: String?, number: String?, zipCode: String?, city: String?, id: Int, createdAt: Date, requesterId: Int, priority: String, additionalRequest: String, deliveryComment: String, phoneNumber: String, status: Status, articles: [RequestArticle], requester: User?) {
        self.street = street
        self.number = number
        self.zipCode = zipCode
        self.city = city
        self.id = id
        self.createdAt = createdAt
        self.requesterId = requesterId
        self.priority = priority
        self.additionalRequest = additionalRequest
        self.deliveryComment = deliveryComment
        self.phoneNumber = phoneNumber
        self.status = status
        self.articles = articles
        self.requester = requester
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case street
        case number
        case zipCode
        case city
        case id
        case createdAt = "created_at"
        case requesterId
        case priority
        case additionalRequest
        case deliveryComment
        case phoneNumber
        case status
        case articles
        case requester
    }

}
