//
// ResponseTokenDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ResponseTokenDto: Codable {

    /** seconds until expiration */
    public var expiresIn: Int
    /** jwt token */
    public var accessToken: String
    /** user id */
    public var id: Int

    public init(expiresIn: Int, accessToken: String, id: Int) {
        self.expiresIn = expiresIn
        self.accessToken = accessToken
        self.id = id
    }

}
