//
// ShoppingList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ShoppingList: Codable {

    public enum Status: String, Codable, CaseIterable {
        case active = "active"
        case canceled = "canceled"
        case completed = "completed"
    }
    public var id: Int
    public var owner: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var status: Status = .active
    public var requests: [ShoppingListRequest]

    public init(id: Int, owner: Int, createdAt: Date, updatedAt: Date, status: Status, requests: [ShoppingListRequest]) {
        self.id = id
        self.owner = owner
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.status = status
        self.requests = requests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case owner
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case status
        case requests
    }

}
