//
// ShoppingListFormDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ShoppingListFormDto: Codable {

    public enum Status: String, Codable, CaseIterable {
        case active = "active"
        case canceled = "canceled"
        case completed = "completed"
    }
    /** List of request IDs */
    public var requests: Int
    public var status: Status? = .active

    public init(requests: Int, status: Status?) {
        self.requests = requests
        self.status = status
    }

}
