//
// TokenDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TokenDto: Codable { 


    public var accessToken: String

    public init(accessToken: String) {
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case accessToken = "access_token"
    }

}
