//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User: Codable { 


    public enum Role: String, Codable, CaseIterable {
        case helper = "helper"
        case seeker = "seeker"
        case _none = "none"
    }
    public var firstName: String?
    public var lastName: String?
    public var street: String?
    public var number: String?
    public var zipCode: String?
    public var city: String?
    public var id: String
    public var email: String?
    public var role: Role? = ._none
    public var phoneNumber: String?

    public init(firstName: String?, lastName: String?, street: String?, number: String?, zipCode: String?, city: String?, id: String, email: String?, role: Role?, phoneNumber: String?) {
        self.firstName = firstName
        self.lastName = lastName
        self.street = street
        self.number = number
        self.zipCode = zipCode
        self.city = city
        self.id = id
        self.email = email
        self.role = role
        self.phoneNumber = phoneNumber
    }

}
