# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NearBuy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearBuy
  pod 'SnapKit'
  pod 'R.swift'
  pod 'XCGLogger'

  target 'NearBuyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
