default_platform(:ios)

platform :ios do
  lane :bootstrap do
    cocoapods(
      clean: true,
      deployment: true
    )
  end

  lane :lint do
    swiftlint(
      executable: 'Pods/SwiftLint/swiftlint',
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  desc "Run the tests"
  lane :test do
    bootstrap
    lint
    scan(
      workspace: "Nexd.xcworkspace",
      scheme: "Nexd"
    )
  end

  desc "Create screenshots"
  lane :create_screenshots do
    bootstrap
    snapshot(output_directory: "./fastlane/screenshots")
    frameit(path: "./fastlane/screenshots")
  end

  desc "Build for distribution (via App Store and TestFlight)"
  lane :testflight_beta do
    bootstrap
    increment_build_number(
      build_number: ENV['GITHUB_RUN_NUMBER']
    )
    setup_ci
    match(
      storage_mode: "git",
      type: "development",
      readonly: true,
      git_url: "https://github.com/schroepf/next-ios-codesigning.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV['MATCH_GIT_BASIC_AUTHORIZATION']}"),
      app_identifier: "app.nexd.apple"
    )
    match(
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      git_url: "https://github.com/schroepf/next-ios-codesigning.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV['MATCH_GIT_BASIC_AUTHORIZATION']}"),
      app_identifier: "app.nexd.apple"
    )
    build_app(
      workspace: "Nexd.xcworkspace",
      scheme: "Nexd",
      export_options: {
        method: "app-store",
        signingCertificate: "Apple Distribution: Tobias Schroepf",
      }
    )
    upload_to_testflight(
      username: "mista.tee.apps@gmail.com",
      skip_waiting_for_build_processing: true,
      apple_id: '1505194845',
      reject_build_waiting_for_review: true
    )
  end
end
