# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :bootstrap do
    cocoapods(
      clean: true,
      deployment: true
    )
  end

  lane :lint do
    swiftlint(
      executable: 'Pods/SwiftLint/swiftlint',
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  desc "Run the tests"
  lane :test do
    bootstrap
    lint
    scan(
      workspace: "Nexd.xcworkspace",
      scheme: "Nexd"
    )
  end

  desc "Build for distribution (via App Store and TestFlight)"
  lane :testflight_beta do
    bootstrap
    increment_build_number(
      build_number: ENV['GITHUB_RUN_NUMBER']
    )
    match(
      storage_mode: "git",
      type: "development",
      readonly: true,
      git_url: "https://github.com/schroepf/next-ios-codesigning.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV['MATCH_GIT_BASIC_AUTHORIZATION']}"),
      app_identifier: "app.nexd.apple"
    )
    match(
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      git_url: "https://github.com/schroepf/next-ios-codesigning.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV['MATCH_GIT_BASIC_AUTHORIZATION']}"),
      app_identifier: "app.nexd.apple"
    )
    build_app(
      workspace: "Nexd.xcworkspace",
      scheme: "Nexd",
      codesigning_identity: "Apple Distribution: Tobias Schroepf",
      export_options: {
        method: "app-store"
      }
    )
    upload_to_testflight(
      username: "mista.tee.apps@gmail.com"
    )
  end
end
