//
// CreateShoppingListDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateShoppingListDto: Codable {

    public enum Status: String, Codable { 
        case active = "active"
        case canceled = "canceled"
        case completed = "completed"
    }
    /** List of request IDs */
    public var requests: [Int]
    public var status: Status?

    public init(requests: [Int], status: Status?) {
        self.requests = requests
        self.status = status
    }


}

