//
// CreateArticleDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateArticleDto: Codable {

    /** Name of the article, should also contain the unit. */
    public var name: String

    public init(name: String) {
        self.name = name
    }


}

