//
// CreateRequestDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateRequestDto: Codable {

    /** List of articles */
    public var articles: [CreateRequestArticleDto]
    public var address: String
    public var zipCode: String
    public var city: String
    public var additionalRequest: String
    public var deliveryComment: String
    public var phoneNumber: String

    public init(articles: [CreateRequestArticleDto], address: String, zipCode: String, city: String, additionalRequest: String, deliveryComment: String, phoneNumber: String) {
        self.articles = articles
        self.address = address
        self.zipCode = zipCode
        self.city = city
        self.additionalRequest = additionalRequest
        self.deliveryComment = deliveryComment
        self.phoneNumber = phoneNumber
    }


}

