//
// Request.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Request: Codable {

    public var _id: Int
    public var createdAt: Date
    public var requester: Int
    public var priority: String
    public var additionalRequest: String
    public var address: String
    public var zipCode: String
    public var city: String
    public var deliveryComment: String
    public var phoneNumber: String
    public var status: String
    public var articles: [RequestArticle]

    public init(_id: Int, createdAt: Date, requester: Int, priority: String, additionalRequest: String, address: String, zipCode: String, city: String, deliveryComment: String, phoneNumber: String, status: String, articles: [RequestArticle]) {
        self._id = _id
        self.createdAt = createdAt
        self.requester = requester
        self.priority = priority
        self.additionalRequest = additionalRequest
        self.address = address
        self.zipCode = zipCode
        self.city = city
        self.deliveryComment = deliveryComment
        self.phoneNumber = phoneNumber
        self.status = status
        self.articles = articles
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdAt = "created_at"
        case requester
        case priority
        case additionalRequest
        case address
        case zipCode
        case city
        case deliveryComment
        case phoneNumber
        case status
        case articles
    }

}

