//
// RequestArticleStatusDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestArticleStatusDto: Codable {

    public var articleDone: Bool

    public init(articleDone: Bool) {
        self.articleDone = articleDone
    }


}

