//
// RequestEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestEntity: Codable {

    public var street: String?
    public var number: String?
    public var zipCode: String
    public var city: String
    public var _id: Int
    public var createdAt: Date
    public var requesterId: Int
    public var priority: String
    public var additionalRequest: String
    public var deliveryComment: String
    public var phoneNumber: String
    public var status: String
    public var articles: [RequestArticle]
    public var requester: User

    public init(street: String?, number: String?, zipCode: String, city: String, _id: Int, createdAt: Date, requesterId: Int, priority: String, additionalRequest: String, deliveryComment: String, phoneNumber: String, status: String, articles: [RequestArticle], requester: User) {
        self.street = street
        self.number = number
        self.zipCode = zipCode
        self.city = city
        self._id = _id
        self.createdAt = createdAt
        self.requesterId = requesterId
        self.priority = priority
        self.additionalRequest = additionalRequest
        self.deliveryComment = deliveryComment
        self.phoneNumber = phoneNumber
        self.status = status
        self.articles = articles
        self.requester = requester
    }

    public enum CodingKeys: String, CodingKey { 
        case street
        case number
        case zipCode
        case city
        case _id = "id"
        case createdAt = "created_at"
        case requesterId
        case priority
        case additionalRequest
        case deliveryComment
        case phoneNumber
        case status
        case articles
        case requester
    }

}

