//
// ShoppingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShoppingList: Codable {

    public var _id: Int
    public var owner: Int
    public var status: String
    public var requests: [ShoppingListRequest]

    public init(_id: Int, owner: Int, status: String, requests: [ShoppingListRequest]) {
        self._id = _id
        self.owner = owner
        self.status = status
        self.requests = requests
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case owner
        case status
        case requests
    }

}

