//
// ShoppingListRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShoppingListRequest: Codable {

    public var requestId: Int

    public init(requestId: Int) {
        self.requestId = requestId
    }


}

