//
// UpdateUserDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateUserDto: Codable {

    public enum Role: String, Codable { 
        case helper = "helper"
        case seeker = "seeker"
    }
    public var firstName: String
    public var lastName: String
    public var role: Role
    public var address: String?
    public var telephone: String?

    public init(firstName: String, lastName: String, role: Role, address: String?, telephone: String?) {
        self.firstName = firstName
        self.lastName = lastName
        self.role = role
        self.address = address
        self.telephone = telephone
    }


}

