//
// RequestArticleStatusDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RequestArticleStatusDto: Codable {

    public var articleDone: Bool

    public init(articleDone: Bool) {
        self.articleDone = articleDone
    }

}
