//
// ShoppingListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ShoppingListRequest: Codable {

    public var requestId: Int

    public init(requestId: Int) {
        self.requestId = requestId
    }

}
